author = "ycwang"
baseURL = "/"
languageCode = "zh-cn"
copyright = "Copyright © 2008–2020, ycwang; all rights reserved."
paginate = 8
title = "ycwang's Blog"
theme = "alageek"

[params]
copyright = "© 2020 by ycwang"
copyrightUrl = "https://blog.ycwang.me"
description = "Hugo alaGeek Theme"
faviconfile = "https://gokmengorgen.net/img/laughing-man-favicon.png"
latestpostcount = 8
highlightjs = true
highlightjslanguages = [ "bash", "cpp", "python" ]
toc = true
posts_navigation = true
progressively = true
github = "https://github.com/wangyongcong"
telegram = "https://t.me/mootaki"
twitter = "https://twitter.com/wangyongcong"
email = "wangyongcong@gmail.com"

[[menu.primary]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 10

[[menu.primary]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20

[[menu.footer]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 50
